### ISSUE TITLE
Unity 5.4.0 introduces breaking API change

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Unity#64]
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.String Unity.Registration.IContainerRegistration.get_Name()'.
   at NServiceBus.Unity.UnityObjectBuilder..ctor(IUnityContainer container, Boolean owned)
   at NServiceBus.UnityBuilder.CreateContainer(ReadOnlySettings settings)
   at NServiceBus.EndpointConfiguration.UseContainer(Type definitionType)
   at Program.<Main>d__0.MoveNext() in S:\particular\docs.particular.net\samples\dependency-injection\unity\Unity_8\Sample\Program.cs:line 17

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>()
```

**Comment by ramonsmits** [comment]
Submitted issue https://github.com/unitycontainer/unity/issues/171

**Comment by ramonsmits** [comment]
[Tried to compare the packages http://apicomparer.particular.net/compare/unity/5.3.2...5.4.0 but unfortunately getting an OutOfMemoryException](https://github.com/ParticularLabs/APIComparer/issues/82)

**Comment by ramonsmits** [comment]
A new version will be released reverting the breaking change based on the following comment:

- https://github.com/unitycontainer/unity/issues/171#issuecomment-352751035

**Comment by ramonsmits** [comment]
New version also broken https://github.com/unitycontainer/unity/issues/180

**Comment by ramonsmits** [comment]
Breaking API change, requires a recompile thus a new release targeting Unity 5.5+

**Comment by patrickrobbins** [comment]
+1.  please publish the current nuget packages with an updated maximum unity target of 5.3.0, and also please create a new nuget package that targets unity 5.5

**Comment by patrickrobbins** [comment]
I have submitted a pull request to fix this issue #66

**Comment by WilliamBZA** [comment]
Thanks @patrickrobbins, we're busy reviewing it!

**Comment by WilliamBZA** [comment]
PR merged, I'll create a backported version and release a new beta of this version

**Comment by WilliamBZA** [comment]
Beta 3 with support for unity 5.5.0 is on myget

**Comment by ramonsmits** [comment]
@WilliamBZA I think you refer to https://www.nuget.org/packages/NServiceBus.Unity/9.0.0-beta0003 but I do not see the fix for core 6.
